Task3
bend-is/avto-dev-go-lang-lessons pull request #4
Opened 2020-11-24 17:57 UTC by bend-is

Add task 3

2020-11-25 09:21 UTC, korjavin requested changes

2020-11-25 09:21 UTC, korjavin commented on task3/main.go
> +	for line, err := bufR.ReadString('\n'); err != io.EOF; line, err = bufR.ReadString('\n') {
Обычно используют scanner

2020-11-25 09:21 UTC, korjavin commented on task3/main.go
> +		fmt.Printf("error occurred whlie opening file %v: %v", filePath, err)
давай подключим линтер на проверку опечаток

2020-11-25 09:21 UTC, korjavin commented on task3/main.go
> +		fmt.Printf("'%v' was repeated: %v time\n", v, sMap.GetCount(v))
%v нужен когда не знаем тип

2020-11-25 09:21 UTC, korjavin commented on task3/main.go
> +func CountWords(r io.Reader) (*sortedmap.SortedMap, error) {
Давай сделаем pkg

2020-11-25 09:21 UTC, korjavin commented on task3/main.go
> +		for i := 1; i < len(words)-1; i++ {
а можем тут range использовать?

2020-11-26 07:40 UTC, bend-is commented on task3/main.go
> +	for line, err := bufR.ReadString('\n'); err != io.EOF; line, err = bufR.ReadString('\n') {
Заменил

2020-11-26 07:42 UTC, bend-is commented on task3/main.go
> +		fmt.Printf("error occurred whlie opening file %v: %v", filePath, err)
Создал конфиг для `golangci`. И наконец то вдруг заработал линтер =). Но `misspell` все равно не хочет видеть эту ошибку. Находит например `occured` но не находит `whlie`

2020-11-26 07:42 UTC, bend-is commented on task3/main.go
> +		fmt.Printf("'%v' was repeated: %v time\n", v, sMap.GetCount(v))
Понял, заменил!

2020-11-26 07:42 UTC, bend-is commented on task3/main.go
> +func CountWords(r io.Reader) (*sortedmap.SortedMap, error) {
Сделал

2020-11-26 07:43 UTC, bend-is commented on task3/main.go
> +		for i := 1; i < len(words)-1; i++ {
Сделано

2020-11-26 08:26 UTC, korjavin commented on task3/main.go
> +		fmt.Printf("error occurred whlie opening file %v: %v", filePath, err)
о, кстати да.

Проверял так
`golangci-lint run --disable-all -E misspell`

2020-11-26 08:27 UTC, korjavin commented
По коду (стилю) замечаний нет.

Логику пока не валидировал.

2020-12-01 11:43 UTC, korjavin commented
Норм, мержим

2020-12-01 11:43 UTC, korjavin approved these changes

2020-12-01 12:21 UTC, merged